apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:4
        name: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379